In [1]:
import sklearn

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("dataset1.csv")
df2=pd.read_csv("dataset2.csv")
df3=pd.read_csv("dataset3.csv")

In [4]:
df.head()

Dst Port  Protocol            Timestamp  Flow Duration  Tot Fwd Pkts  \
0       443         6  02/03/2018 08:47:38         141385             9   
1     49684         6  02/03/2018 08:47:38            281             2   
2       443         6  02/03/2018 08:47:40         279824            11   
3       443         6  02/03/2018 08:47:40            132             2   
4       443         6  02/03/2018 08:47:41         274016             9   

   Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0             7              553           3773.0              202   
1             1               38              0.0               38   
2            15             1086          10527.0              385   
3             0                0              0.0                0   
4            13             1285           6141.0              517   

   Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                0  ...                20          0.0         0.0   
1                0  ...                20          0.0         0.0   
2                0  ...                20          0.0         0.0   
3                0  ...                20          0.0         0.0   
4                0  ...                20          0.0         0.0   

   Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min   Label  
0         0.0         0.0        0.0       0.0       0.0       0.0  Benign  
1         0.0         0.0        0.0       0.0       0.0       0.0  Benign  
2         0.0         0.0        0.0       0.0       0.0       0.0  Benign  
3         0.0         0.0        0.0       0.0       0.0       0.0  Benign  
4         0.0         0.0        0.0       0.0       0.0       0.0  Benign  

[5 rows x 80 columns]

In [5]:
df2.head()

Dst Port Protocol            Timestamp Flow Duration Tot Fwd Pkts  \
0        0        0  01/03/2018 08:17:11     115307855            5   
1        0        0  01/03/2018 08:20:07      60997457            2   
2       67       17  01/03/2018 08:17:18      61149019            5   
3        0        0  01/03/2018 08:22:09      60997555            2   
4        0        0  01/03/2018 08:24:11      61997503            3   

  Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max  \
0            0               0               0               0   
1            0               0               0               0   
2            0            1500               0             300   
3            0               0               0               0   
4            0               0               0               0   

  Fwd Pkt Len Min  ... Fwd Seg Size Min Active Mean Active Std Active Max  \
0               0  ...                0     1812348          0    1812348   
1               0  ...                0           0          0          0   
2             300  ...                8     3530939          0    3530939   
3               0  ...                0           0          0          0   
4               0  ...                0      999909          0     999909   

  Active Min Idle Mean     Idle Std  Idle Max  Idle Min   Label  
0    1812348  56700000  6010057.622  61000000  52500000  Benign  
1          0  61000000            0  61000000  61000000  Benign  
2    3530939  19200000     12500000  32600000   7999725  Benign  
3          0  61000000            0  61000000  61000000  Benign  
4     999909  61000000            0  61000000  61000000  Benign  

[5 rows x 80 columns]

In [6]:
df3.head()

Dst Port  Protocol            Timestamp  Flow Duration  Tot Fwd Pkts  \
0         0         0  14/02/2018 08:31:01      112641719             3   
1         0         0  14/02/2018 08:33:50      112641466             3   
2         0         0  14/02/2018 08:36:39      112638623             3   
3        22         6  14/02/2018 08:40:13        6453966            15   
4        22         6  14/02/2018 08:40:23        8804066            14   

   Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0             0                0                0                0   
1             0                0                0                0   
2             0                0                0                0   
3            10             1239             2273              744   
4            11             1143             2209              744   

   Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                0  ...                 0          0.0         0.0   
1                0  ...                 0          0.0         0.0   
2                0  ...                 0          0.0         0.0   
3                0  ...                32          0.0         0.0   
4                0  ...                32          0.0         0.0   

   Active Max  Active Min   Idle Mean    Idle Std  Idle Max  Idle Min   Label  
0           0           0  56320859.5  139.300036  56320958  56320761  Benign  
1           0           0  56320733.0  114.551299  56320814  56320652  Benign  
2           0           0  56319311.5  301.934596  56319525  56319098  Benign  
3           0           0         0.0    0.000000         0         0  Benign  
4           0           0         0.0    0.000000         0         0  Benign  

[5 rows x 80 columns]

In [7]:
df['Label'].unique()

array(['Benign', 'Bot'], dtype=object)

In [8]:
df2['Label'].unique()

array(['Benign', 'Label', 'Infilteration'], dtype=object)

In [9]:
df3['Label'].unique()

array(['Benign', 'FTP-BruteForce', 'SSH-Bruteforce'], dtype=object)

In [10]:
df['Label']=np.where(df['Label']!='Benign',"MALACIOUS","SAFE")

In [11]:
df['Label'].unique()

array(['SAFE', 'MALACIOUS'], dtype=object)

In [12]:
count_safe=(df['Label']=='SAFE').sum()
count_malacious=(df['Label']=='MALACIOUS').sum()
print(count_safe)
print(count_malacious)
imbalance_ratio=count_safe/count_malacious
print(imbalance_ratio)

762384
286191
2.6638992840445717


In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype  
---  ------             --------------    -----  
 0   Dst Port           1048575 non-null  int64  
 1   Protocol           1048575 non-null  int64  
 2   Timestamp          1048575 non-null  object 
 3   Flow Duration      1048575 non-null  int64  
 4   Tot Fwd Pkts       1048575 non-null  int64  
 5   Tot Bwd Pkts       1048575 non-null  int64  
 6   TotLen Fwd Pkts    1048575 non-null  int64  
 7   TotLen Bwd Pkts    1048575 non-null  float64
 8   Fwd Pkt Len Max    1048575 non-null  int64  
 9   Fwd Pkt Len Min    1048575 non-null  int64  
 10  Fwd Pkt Len Mean   1048575 non-null  float64
 11  Fwd Pkt Len Std    1048575 non-null  float64
 12  Bwd Pkt Len Max    1048575 non-null  int64  
 13  Bwd Pkt Len Min    1048575 non-null  int64  
 14  Bwd Pkt Len Mean   1048575 non-null  float64
 15  Bwd Pkt Len Std    1048575 non-n

In [14]:
print(df.columns[df.isnull().any()])

Index(['Flow Byts/s'], dtype='object')


In [15]:
df=df.dropna(axis=0)

In [16]:
print(df.columns[df.isnull().any()])

Index([], dtype='object')


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1046017 entries, 0 to 1048574
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype  
---  ------             --------------    -----  
 0   Dst Port           1046017 non-null  int64  
 1   Protocol           1046017 non-null  int64  
 2   Timestamp          1046017 non-null  object 
 3   Flow Duration      1046017 non-null  int64  
 4   Tot Fwd Pkts       1046017 non-null  int64  
 5   Tot Bwd Pkts       1046017 non-null  int64  
 6   TotLen Fwd Pkts    1046017 non-null  int64  
 7   TotLen Bwd Pkts    1046017 non-null  float64
 8   Fwd Pkt Len Max    1046017 non-null  int64  
 9   Fwd Pkt Len Min    1046017 non-null  int64  
 10  Fwd Pkt Len Mean   1046017 non-null  float64
 11  Fwd Pkt Len Std    1046017 non-null  float64
 12  Bwd Pkt Len Max    1046017 non-null  int64  
 13  Bwd Pkt Len Min    1046017 non-null  int64  
 14  Bwd Pkt Len Mean   1046017 non-null  float64
 15  Bwd Pkt Len Std    1046017 non-n

In [18]:
le=LabelEncoder()
df['Timestamp']=le.fit_transform(df['Timestamp'])
df['Label']=le.fit_transform(df['Label'])

In [19]:
np.isfinite(df)

Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  \
0            True      True       True           True          True   
1            True      True       True           True          True   
2            True      True       True           True          True   
3            True      True       True           True          True   
4            True      True       True           True          True   
...           ...       ...        ...            ...           ...   
1048570      True      True       True           True          True   
1048571      True      True       True           True          True   
1048572      True      True       True           True          True   
1048573      True      True       True           True          True   
1048574      True      True       True           True          True   

         Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0                True             True             True             True   
1                True             True             True             True   
2                True             True             True             True   
3                True             True             True             True   
4                True             True             True             True   
...               ...              ...              ...              ...   
1048570          True             True             True             True   
1048571          True             True             True             True   
1048572          True             True             True             True   
1048573          True             True             True             True   
1048574          True             True             True             True   

         Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                   True  ...              True         True        True   
1                   True  ...              True         True        True   
2                   True  ...              True         True        True   
3                   True  ...              True         True        True   
4                   True  ...              True         True        True   
...                  ...  ...               ...          ...         ...   
1048570             True  ...              True         True        True   
1048571             True  ...              True         True        True   
1048572             True  ...              True         True        True   
1048573             True  ...              True         True        True   
1048574             True  ...              True         True        True   

         Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  \
0              True        True       True      True      True      True   
1              True        True       True      True      True      True   
2              True        True       True      True      True      True   
3              True        True       True      True      True      True   
4              True        True       True      True      True      True   
...             ...         ...        ...       ...       ...       ...   
1048570        True        True       True      True      True      True   
1048571        True        True       True      True      True      True   
1048572        True        True       True      True      True      True   
1048573        True        True       True      True      True      True   
1048574        True        True       True      True      True      True   

         Label  
0         True  
1         True  
2         True  
3         True  
4         True  
...        ...  
1048570   True  
1048571   True  
1048572   True  
1048573   True  
1048574   True  

[1046017 rows x 80 columns]

In [20]:
df=df[np.isfinite(df).all(1)]

In [21]:
df

Dst Port  Protocol  Timestamp  Flow Duration  Tot Fwd Pkts  \
0             443         6      16283         141385             9   
1           49684         6      16283            281             2   
2             443         6      16285         279824            11   
3             443         6      16285            132             2   
4             443         6      16286         274016             9   
...           ...       ...        ...            ...           ...   
1048570      3389         6       4098        3982183            14   
1048571      3389         6       4102        3802316            14   
1048572      3389         6       4105        4004239            14   
1048573      3389         6       4109        3998435            14   
1048574      3389         6       4113        3972651            14   

         Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
0                   7              553           3773.0              202   
1                   1               38              0.0               38   
2                  15             1086          10527.0              385   
3                   0                0              0.0                0   
4                  13             1285           6141.0              517   
...               ...              ...              ...              ...   
1048570             8             1442           1731.0              725   
1048571             8             1440           1731.0              725   
1048572             8             1459           1731.0              741   
1048573             8             1459           1731.0              741   
1048574             8             1439           1731.0              725   

         Fwd Pkt Len Min  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                      0  ...                20          0.0         0.0   
1                      0  ...                20          0.0         0.0   
2                      0  ...                20          0.0         0.0   
3                      0  ...                20          0.0         0.0   
4                      0  ...                20          0.0         0.0   
...                  ...  ...               ...          ...         ...   
1048570                0  ...                20          0.0         0.0   
1048571                0  ...                20          0.0         0.0   
1048572                0  ...                20          0.0         0.0   
1048573                0  ...                20          0.0         0.0   
1048574                0  ...                20          0.0         0.0   

         Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  \
0               0.0         0.0        0.0       0.0       0.0       0.0   
1               0.0         0.0        0.0       0.0       0.0       0.0   
2               0.0         0.0        0.0       0.0       0.0       0.0   
3               0.0         0.0        0.0       0.0       0.0       0.0   
4               0.0         0.0        0.0       0.0       0.0       0.0   
...             ...         ...        ...       ...       ...       ...   
1048570         0.0         0.0        0.0       0.0       0.0       0.0   
1048571         0.0         0.0        0.0       0.0       0.0       0.0   
1048572         0.0         0.0        0.0       0.0       0.0       0.0   
1048573         0.0         0.0        0.0       0.0       0.0       0.0   
1048574         0.0         0.0        0.0       0.0       0.0       0.0   

         Label  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
1048570      1  
1048571      1  
1048572      1  
1048573      1  
1048574      1  

[1044525 rows x 80 columns]

In [22]:
df.describe()

Dst Port      Protocol     Timestamp  Flow Duration  Tot Fwd Pkts  \
count  1.044525e+06  1.044525e+06  1.044525e+06   1.044525e+06  1.044525e+06   
mean   8.266766e+03  8.057796e+00  1.623202e+04   1.155885e+07  5.902530e+00   
std    1.496231e+04  4.439372e+00  9.178054e+03   3.017092e+07  8.920527e+01   
min    0.000000e+00  0.000000e+00  0.000000e+00   1.000000e+00  1.000000e+00   
25%    8.000000e+01  6.000000e+00  8.312000e+03   5.190000e+02  2.000000e+00   
50%    3.389000e+03  6.000000e+00  1.662500e+04   1.127400e+04  3.000000e+00   
75%    8.080000e+03  6.000000e+00  2.487900e+04   2.221014e+06  7.000000e+00   
max    6.553400e+04  1.700000e+01  3.142400e+04   1.200000e+08  4.315900e+04   

       Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  Fwd Pkt Len Max  \
count  1.044525e+06     1.044525e+06     1.044525e+06     1.044525e+06   
mean   7.010040e+00     3.935511e+02     5.291713e+03     2.111953e+02   
std    2.133700e+02     2.163833e+03     3.094749e+05     2.671786e+02   
min    0.000000e+00     0.000000e+00     0.000000e+00     0.000000e+00   
25%    0.000000e+00     0.000000e+00     0.000000e+00     0.000000e+00   
50%    1.000000e+00     6.400000e+01     1.290000e+02     4.600000e+01   
75%    5.000000e+00     3.690000e+02     5.820000e+02     3.260000e+02   
max    6.924100e+04     1.100627e+06     1.010000e+08     1.711000e+03   

       Fwd Pkt Len Min  ...  Fwd Seg Size Min   Active Mean    Active Std  \
count     1.044525e+06  ...      1.044525e+06  1.044525e+06  1.044525e+06   
mean      8.273807e+00  ...      1.744416e+01  1.234346e+05  6.154744e+04   
std       2.098046e+01  ...      5.187126e+00  2.087119e+06  1.264132e+06   
min       0.000000e+00  ...      0.000000e+00  0.000000e+00  0.000000e+00   
25%       0.000000e+00  ...      2.000000e+01  0.000000e+00  0.000000e+00   
50%       0.000000e+00  ...      2.000000e+01  0.000000e+00  0.000000e+00   
75%       0.000000e+00  ...      2.000000e+01  0.000000e+00  0.000000e+00   
max       1.460000e+03  ...      4.400000e+01  1.110000e+08  7.490000e+07   

         Active Max    Active Min     Idle Mean      Idle Std      Idle Max  \
count  1.044525e+06  1.044525e+06  1.044525e+06  1.044525e+06  1.044525e+06   
mean   1.912618e+05  8.337649e+04  4.799736e+06  1.068351e+05  4.882636e+06   
std    2.766778e+06  1.763232e+06  1.744425e+07  1.465423e+06  1.759949e+07   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
max    1.110000e+08  1.110000e+08  1.200000e+08  7.590000e+07  1.200000e+08   

           Idle Min         Label  
count  1.044525e+06  1.044525e+06  
mean   4.695151e+06  7.260085e-01  
std    1.736415e+07  4.460049e-01  
min    0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  
50%    0.000000e+00  1.000000e+00  
75%    0.000000e+00  1.000000e+00  
max    1.200000e+08  1.000000e+00  

[8 rows x 80 columns]

In [23]:
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [24]:
x=df.drop(['Label'],axis=1).values
y=df['Label'].values

In [25]:
x

array([[4.4300e+02, 6.0000e+00, 1.6283e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.9684e+04, 6.0000e+00, 1.6283e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [4.4300e+02, 6.0000e+00, 1.6285e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [3.3890e+03, 6.0000e+00, 4.1050e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.3890e+03, 6.0000e+00, 4.1090e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.3890e+03, 6.0000e+00, 4.1130e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [26]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [27]:
robust=RobustScaler()
x_scaled=robust.fit_transform(x)

minmax=MinMaxScaler()
x_scaled=minmax.fit_transform(x_scaled)

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

In [29]:
x_train

array([[3.35703604e-04, 3.52941176e-01, 7.06466395e-02, ...,
        0.00000000e+00, 2.00833333e-01, 2.00833333e-01],
       [1.23294778e-01, 3.52941176e-01, 8.36876273e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.92916654e-01, 3.52941176e-01, 3.31370927e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.23294778e-01, 3.52941176e-01, 7.99643585e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.79036836e-03, 3.52941176e-01, 8.05435336e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.75963622e-01, 3.52941176e-01, 3.24592668e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [30]:
x_test

array([[8.08740501e-04, 1.00000000e+00, 6.36615326e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.79036836e-03, 3.52941176e-01, 1.61405295e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.23294778e-01, 3.52941176e-01, 7.61806263e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [8.08740501e-04, 1.00000000e+00, 7.61583503e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.23294778e-01, 3.52941176e-01, 3.06453666e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.23294778e-01, 3.52941176e-01, 1.22390530e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [31]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [32]:
y_test

array([1, 1, 0, ..., 1, 0, 0])

In [33]:
X_train_df = pd.DataFrame(x_train) 
X_test_df = pd.DataFrame(x_test)
Y_train_df = pd.DataFrame(y_train)
Y_test_df = pd.DataFrame(y_test)

In [34]:
X_train_df.to_csv("X_train_dataset01.csv",index=False)
X_test_df.to_csv("X_test_dataset01.csv",index=False)
Y_train_df.to_csv("Y_train_dataset01.csv",index=False)
Y_test_df.to_csv("Y_test_dataset01.csv",index=False)

In [35]:
x_train.shape
x_test.shape

(208905, 79)

# Model

In [38]:
# Importing Libraries

from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

### 1. Ada Boast Algorithm

In [42]:
# Fitting and Training 
adaboost_model = AdaBoostClassifier(n_estimators=50, random_state=42)
adaboost_model.fit(x_train, y_train.ravel())

AdaBoostClassifier(random_state=42)

In [43]:
# Prediction
adaboost_predict = adaboost_model.predict(x_test)

In [44]:
# Result
adaboost_accuracy = accuracy_score(y_test, adaboost_predict)
print("AdaBoost Classifier Accuracy:", adaboost_accuracy)

AdaBoost Classifier Accuracy: 0.9999473444867284


### 2. KNN Algorithm

In [ ]:
# Fitting and Training 
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train, y_train.ravel())

In [ ]:
# Prediction
knn_predict = knn_model.predict(x_test)

In [ ]:
# Result
knn_accuracy = accuracy_score(y_test, knn_predict)
print("KNN Classifier Accuracy:", knn_accuracy)

### 3. Decision Tree Algorithm

In [ ]:
# Fitting and Training 
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit((x_train, y_train.ravel())

In [ ]:
# Prediction
dt_predict = dt_model.predict(x_test)

In [ ]:
# Result
dt_accuracy = accuracy_score(y_test, dt_predict)
print("Decision Tree Classifier Accuracy:", dt_accuracy)